### ISSUE TITLE
文中的公式未显示

### ISSUE THREAD

**Issue by xiaoshuwen1995** [songyingxin/NLPer-Interview#1]
作者你好，你的工作很仔细，感谢。

但是我在阅读的时候发现一个小问题，第7章的词向量-Word2Vec文章中，所有的公式都没有正常显示，例如【$w_t$ 】。在其他文章中暂时没有发现这个问题，希望你能抽空修改。

谢谢！

**Comment by songyingxin** [comment]
你是用 typora 打开的吗？ 我这边显示没有问题呀

**Comment by xiaoshuwen1995** [comment]
> 你是用 typora 打开的吗？ 我这边显示没有问题呀

我是用Typora打开的。例如下面这一段中，【$W_{V \times N}$】就是公式显示错误：

如上图是一个两层的神经网络，其实在训练语言模型的过程中考虑到效率等问题，常常采用浅层的神经网络来训练，并取第一层的参数如上图就是 $W_{V \times N}$ 来作为最终的词向量矩阵（参考 [语言模型：从n元模型到NNLM](https://zhuanlan.zhihu.com/p/43453548)）。

**Comment by songyingxin** [comment]
我这没问题，你是不是typora中内联公式支持没有开启？

**Comment by songyingxin** [comment]
我重新上传了，你再pull 一下看看

**Comment by xiaoshuwen1995** [comment]
> 我重新上传了，你再pull 一下看看

确实是内联公式没有开启的原因！设置完已经可以正常打开了~

感谢~Thanks♪(･ω･)ﾉ
