### ISSUE TITLE
提一些看到的错误

### ISSUE THREAD

**Issue by hialoha** [songyingxin/NLPer-Interview#2]
1.无伤大雅的错别字。
基础理论 - 目标函数，损失函数，代价函数
QA
1. Sigmoid 为何与交叉熵搭配**_二_**不用二次方代价函数

**Comment by songyingxin** [comment]
哈哈哈哈，好的，感谢，不过可能没时间去review了

**Comment by jackielokkk** [comment]
请问那些公式怎么感觉有点奇怪

**Comment by songyingxin** [comment]
> 请问那些公式怎么感觉有点奇怪

怎么怪了呢，我用typora写的markdown公式

**Comment by jemmryx** [comment]
> > 请问那些公式怎么感觉有点奇怪
> 
> 怎么怪了呢，我用typora写的markdown公式

<img width="866" alt="image" src="https://user-images.githubusercontent.com/26646576/85872045-d36f8280-b801-11ea-81dd-3384665e53d2.png">
看得太难受了

**Comment by songyingxin** [comment]
> > > 请问那些公式怎么感觉有点奇怪
> > 
> > 
> > 怎么怪了呢，我用typora写的markdown公式
> 
> <img alt="image" width="866" src="https://user-images.githubusercontent.com/26646576/85872045-d36f8280-b801-11ea-81dd-3384665e53d2.png">
> 
> 看得太难受了

为啥我这边没问题，你用啥看的？
